title: ProductDetailsV2ChannelsRequest
description: The market to retrieve results for.
type: string
enum:
  - AMAZON_US
  - AMAZON_UK
  - AMAZON_CA
  - AMAZON_AU
  - AMAZON_MX
  - AMAZON_DE
  - AMAZON_SE
  - AMAZON_FR
  - AMAZON_IT
  - AMAZON_NL
  - AMAZON_PL
  - AMAZON_ES
  - AMAZON_BE
  - AMAZON_TR
  - AMAZON_BR
  - AMAZON_IN
  - AMAZON_AE
  - AMAZON_EG
  - AMAZON_JP
  - AMAZON_SA
  - AMAZON_SG
example: AMAZON_US